# Generated by Django 6.0 on 2025-12-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterkunft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unterkunft',
            options={'verbose_name': 'Unterkunft', 'verbose_name_plural': 'Unterkünfte'},
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bestätigt', 'Bestätigt'), ('abgesagt', 'Abgesagt')], default='offen', max_length=10)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unterkunft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unterkunft.unterkunft')),
            ],
        ),
    ]
