# Generated by Django 6.0 on 2025-12-15 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unterkunft', '0002_alter_unterkunft_options_buchung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unterkunft',
            name='anbieter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unterkuenfte', to=settings.AUTH_USER_MODEL),
        ),
    ]
